version: "3.8"

services:
  product-api:
    build:
      context: ../product-api
    depends_on:
      - db
    volumes:
      - "../product-api:/data/app"
      - "./scripts:/scripts:ro"
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - ../dot-env/product-api/.env
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./resources/mysql/data:/var/lib/mysql"
